config/routes.rb
Rails3App::Application.routes.draw do

  get "logout" => "sessions#destroy", :as => "logout"
  get "login"  => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "dashboard" => "home#show", :as => "dashboard"
  root :to => "home#index"
  
  resources :logins
  resources :users
  resources :sessions
  resources :activations
  resources :password_resets
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:password_reset][:email])
    user.send_confirmation(:password_reset) if user
    redirect_to root_url, :notice => 'Email sent with password reset instructions.'
  end

  def edit
    @user = User.find_by_confirmation_token!(params[:id])
    if !token_expired_and_redirected(@user)
      # render :edit
    end
  end

  def update
    @user = User.find_by_confirmation_token!(params[:id])
    if !token_expired_and_redirected(@user)
      if @user.update_password!(params[:user][:password], params[:user][:password_confirmation])
        redirect_to member_root_url, :notice => 'Your password has been reset. Please log in.'
      else
        render :edit
      end
    end
  end
  
  protected
  
  def token_expired_and_redirected(user)
    if user.confirmation_type != 'password_reset' || user.confirmation_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, :alert => 'Password reset has expired.'
      true
    else
      false
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<div class="page-header">
  <h1>Reset password</h1>
</div>

<%= simple_form_for(@user, :url => password_reset_path(params[:id]), :defaults => { :input_html => { :class => 'input-xlarge' } }) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
  </div>
  
  <div class="form-actions">
    <%= f.submit 'Update Password', :class => "btn-primary" %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<div class="page-header">
  <h1>Reset Password</h1>
</div>

<%= simple_form_for(:password_reset, :url => { :action => :create }, :defaults => { :input_html => { :class => 'input-xlarge' } }) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :email %>
  </div>
  
  <div class="form-actions">
    <%= f.submit 'Reset Password', :class => "btn-primary" %>
  </div>
<% end %>