config/routes.rb
Rails3App::Application.routes.draw do

  get "logout" => "sessions#destroy", :as => "logout"
  get "login"  => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "dashboard" => "home#show", :as => "dashboard"
  root :to => "home#index"
  
  resources :logins
  resources :users
  resources :sessions
  resources :activations
  resources :password_resets
end

app/models/login.rb
class Login < ActiveRecord::Base
  belongs_to :user
  
  attr_accessible :session_id, :user_id, :ip_address, :status, :created_at, :ended_at

  def self.log_in_current_session(session_id, ip_address, user_id)
    login = find(:first, :conditions => ['session_id=? AND status=?', session_id, 'active'])
    if login
      return login if login.user_id == user_id
      login.update_attributes(:ended_at => Time.now, :status => 'logged_out')
    end
    create(:session_id => session_id, :user_id => user_id, :ip_address => ip_address)
  end
  
  def self.log_out_current_session(session_id, ip_address)
    login = find(:first, :conditions => ['session_id=?', session_id])
    if login
      login.update_attributes(:ended_at => Time.now, :status => 'logged_out')
    end
    create(:session_id => session_id, :user_id => User::ANONYMOUS_USER_ID, :ip_address => ip_address)
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  # GET /logins
  # GET /logins.json
  def index
    @logins = Login.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @logins }
    end
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
    @login = Login.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @login }
    end
  end
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/logins/index.html.erb
<div class="page-header">
  <%= link_to new_login_path, :class => 'btn btn-primary' do %>
    <i class="icon-plus icon-white"></i>
    New Login
  <% end %>
  <h1>Logins</h1>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Ip address</th>
      <th>User</th>
      <th>Status</th>
      <th>Started at</th>
      <th>Ended at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
<% @logins.each do |login| %>
    <tr>
      <td><%= login.ip_address %></td>
      <td><%= login.user_id %></td>
      <td><%= login.status %></td>
      <td><%= login.started_at %></td>
      <td><%= login.ended_at %></td>
      <td><%= link_to 'Show', login %></td>
      <td><%= link_to 'Edit', edit_login_path(login) %></td>
      <td><%= link_to 'Destroy', login, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
<% end %>
  </tbody>
</table>

app/views/logins/show.html.erb
<div class="page-header">
  <%= link_to logins_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <%= link_to edit_login_path(@login), :class => 'btn btn-primary' do %>
    <i class="icon-pencil icon-white"></i>
    Edit
  <% end %>
  <h1>Login</h1>
</div>

<dl>
  <dt>Ip Address:</dt>
  <dd><%= @login.ip_address %></dd>

  <dt>User:</dt>
  <dd><%= @login.user_id %></dd>

  <dt>Status:</dt>
  <dd><%= @login.status %></dd>

  <dt>Started at:</dt>
  <dd><%= @login.started_at %></dd>

  <dt>Ended at:</dt>
  <dd><%= @login.ended_at %></dd>

</dl>